### ISSUE TITLE
device_calendar not building in xcode 9

### ISSUE THREAD

**Issue by isoos** [builttoroam/flutter_plugins#61] opened 2018-07-18 07:56 UTC
_From @blaneyneil on July 6, 2018 1:44_

URL: https://pub.dartlang.org/packages/device_calendar#-example-tab-

just a head's up:

The target “device_calendar” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

_Copied from original issue: dart-lang/pub-dartlang-dart#1435_

**Comment by isoos** [comment] 2018-07-18 07:56
@blaneyneil: please file issues to the package's repository. You can check that on the package page, usually the homepage points to it. I'm moving this now.

**Comment by MaikuB** [comment] 2018-07-24 05:59
Thanks @isoos 

@blaneyneil: are you seeing this when you run the example apps as I haven't seen that show up (running Xcode 9.4). You may need to modify the podfile for your iOS head project. Similar to #60

**Comment by blaneyneil** [comment] 2018-07-24 06:09
yep, my bad.  at the time i filed this i had no swift support enabled, and had zero experience with anything other than Obj C plugins.

**Comment by MaikuB** [comment] 2018-07-24 06:14
So you were able to sort this out then? Looking to see if we can close this if you have. Going to update the README with info on what's needed for Obj C iOS head projects. From what I've tried and confirmed to work it involves modifying the Podfile so it should look something like

```
target 'Runner' do
  use_frameworks!
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
```

Not sure if you did the same and haven't gotten a response in #60 where @shinyford mentioned having tried some of the solutions out there but didn't mention if they've tried the above

**Comment by blaneyneil** [comment] 2018-07-25 03:56
well, it was close.  i had it working locally by adding `use_frameworks!` and `config.build_settings['SWIFT_VERSION'] = '4.0'` and was even able to build it, but when archiving on Xcode there were several compilation errors as a result of conflicts with Firestore.

**Comment by MaikuB** [comment] 2018-07-25 22:06
What compilation errors are you seeing?

**Comment by gunhansancar** [comment] 2018-09-11 14:08
Any update on this one? It should be fairly simple to update to Swift version for a small library I guess.

**Comment by MaikuB** [comment] 2018-09-11 20:33
If it's the swift version issue you're seeing then that's actually something you need to change in your iOS project's Podfile as mentioned above and here https://github.com/builttoroam/flutter_plugins/issues/61#issuecomment-407293239

Haven't heard back @blaneyneil about the Firestore issue but there was originally an issue that I saw logged on the main Flutter repo where another developer had problems create an archive in Xcode and this didn't have to do with conflicts with the calendar plugin e.g. https://github.com/flutter/flutter/issues/19149

**Comment by MaikuB** [comment] 2019-05-28 10:43
Closing since there hasn't been any further response. Feel free to re-open or create another issue if you still experience problems

**Closed by MaikuB** 2019-05-28 10:43 UTC
