### ISSUE TITLE
updating an event info does not propagate to retrieveEvents() until app restart

### ISSUE THREAD

**Issue by CoreyCole** [builttoroam/flutter_plugins#125] opened 2019-10-31 19:19 UTC
Repro:
- create an event in device's calendar
- build a flutter app using `device_calendar: 1.0.0+2`
- retrieve the calendar information
```dart
Future<void> getDeviceEvents() async {
  try {
    final permitted = await deviceCal.requestPermissions();
    if (!permitted.data)
      throw 'user denied calendar permissions!';
    final calendars = await deviceCal.retrieveCalendars();
    if (calendars.data == null || calendars.data.length == 0)
      throw 'no device calendars to parse!';
    calendars.data.forEach((calendar) async {
      final events = await DeviceCalendarPlugin().retrieveEvents(calendar.id, RetrieveEventsParams(
        startDate: DateTime.now().subtract(Duration(days: 3)),
        endDate: DateTime.now().add(Duration(days: 3)),
      ));
      if (events.data != null && events.data.length > 0) {
        _parseDeviceEvents(events.data.toList(), calendar);
      }
    });
  } catch (err) {
    print('[CalendarService][getDeviceEvents] ERROR = $err');
  }
}
```
- see the event I created with the `start` time at the date I created it with
- go into device calendar, change the date to a different day
- `flutter clean` & `flutter run -d all`
- retrieve the calendar information again, see the `start` time for the event is **not updated** (it is still the `start` that I originally created it with)

Environment:
- Android 10 (API 29)
- Google calendar
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.5 at /Users/corey/flutter
    • Framework revision 1aedbb1835 (2 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/corey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/corey/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/corey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • ONEPLUS A6000 • 4241cff9 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by nickrandolph** [comment] 2019-10-31 20:07
Hi @CoreyCole , have you confirmed that the calendar date has changed in other apps that access the calendar. Also if you change the event date in Flutter does it reflect in the device calendar?

**Comment by CoreyCole** [comment] 2019-10-31 20:17
@nickrandolph do you have a suggestion for an app I can download on android to see? I'll check now to see if I can change the date using the plugin

**Comment by CoreyCole** [comment] 2019-10-31 20:51
It seems like it is working now. As soon as I update an event time in Google calendar, it is instantly reflected in my flutter app using `device_calendar` plugin. I'll close for now, but keep a close eye to see if I can reliable reproduce it.

**Comment by nickrandolph** [comment] 2019-10-31 20:59
Thanks @CoreyCole

**Comment by CoreyCole** [comment] 2019-12-05 22:06
This issue has resurfaced again, not only for the the time, but the descriptions/title as well. The updates don't come through until I restart the application.

Is the plugin doing any caching of events or does it query the device every time?

**Comment by Brett09** [comment] 2020-01-22 00:12
@CoreyCole are you still experiencing the issue? I've tried the exact steps with the latest release (v3.0.0) in Android and could not reproduce the issue.

If you still are, can you able to try it out with the latest release? (Please note that there are several breaking changes for Attendee and RecurrenceRule models, you'll need to update your code if you're using them)

**Comment by Brett09** [comment] 2020-03-10 00:56
As I said above, I haven't noticed such issue in the latest version and so I'm going to close this for now. Feel free to open a new ticket if you still experience the issue.

fyi, I could be wrong but maybe try with a different device/emulator as it could be a device issue.

**Closed by Brett09** 2020-03-10 00:56 UTC
Labels: question
