### ISSUE TITLE
Attendee details not showing in Calendar,Datetime also reflecting inncorrectly. 

### ISSUE THREAD

**Issue by BryteNyte** [builttoroam/flutter_plugins#131] opened 2019-12-06 09:13 UTC
I am using the example app and testing it on Android. I see that when i create a calendar event and add a Attendee , the attendee isnt showing on the devices calendar but is showing in the example calendar,also i noticed that if i go into my devices calendar the event time date is incorrect but in the example it is correct.

**Comment by Brett09** [comment] 2020-01-09 05:18
Hi,

Which email account have you used to experience the issue? I cannot reproduce this issue with Office 365 and Gmail accounts.

**Comment by Brett09** [comment] 2020-01-22 00:57
Newer version of this plugin (v3.0.0) has been released yesterday (21/01/20) with attendee improvements and UI improvements for the example app and haven't noticed such issue during testing.
It is a breaking change so make sure to change your code following to the example when you’re upgrading the plugin: https://pub.dev/packages/device_calendar#-example-tab-

Also, in the example app, the attendees without a name in the list of events page will not be shown:
```dart
Expanded(
  child: Text(
	_calendarEvent?.attendees
			?.where((a) => a.name?.isNotEmpty ?? false)
			?.map((a) => a.name)
			?.join(', ') ??
		'',
	overflow: TextOverflow.ellipsis,
  ),
)
```
But you should be able to get all attendees when you edit an event.

Closing this ticket for now, feel free to open a new issue ticket if the issue persists.

**Closed by Brett09** 2020-01-22 00:57 UTC
Labels: question
