### ISSUE TITLE
The number of events that can be obtained on Android and iOS is different.

### ISSUE THREAD

**Issue by trap0f** [builttoroam/flutter_plugins#111] opened 2019-08-06 02:52 UTC
Thanks for the useful plug-in.
I have the following problems.
There are two events on the same day of the same calendar.
Executes retrieveEvents.
The number of events that can be obtained on Android and iOS is different.

*device _ calendar: ^ 0.2 .1 + 1
Android: 2 events
iOS: 1 event

*device _ calendar: ^ 0.1 .3
Android: 2 events
iOS: 2 events

Are there any measures?

**Comment by MaikuB** [comment] 2019-08-06 04:11
Please elaborate on what you mean by measures. We haven't any differences in the code between the versions you've tried that would affect the number of events retrieved. We've also tried adding an outlook.com account to both an Android and iOS device that had two events in the calendar. Upon running the example app, it showed that there were two events on both devices so from what we can see, it is working as expected. Please provide steps to reproduce the problem if you're seeing an issue

**Comment by trap0f** [comment] 2019-08-06 13:01
Thank you for checking.
The situation has now improved.

My situation was as follows.

•App
 device_calendar 0.2.1+1
 flutter_plugins/device_calendar/example/

•Calendar
 Google Calendar
 (iOS: Settings > Passwords & Accounts > Add Account > Google)

•Event (All day: No)
 8/6/2019 1:30 PM - 2:00 PM event1
 8/6/2019 3:30 PM - 5:30 PM event2

•Emulator / Simulator
 Android: Pixel 3 XL API 28 Android 9.0
 iOS: iPhone Xs Max & iPhone 7 iOS 12.4

•Result
 Android: event1, event2
 iOS: event2

I changed my iOS language setting (Japanese -> English -> Japanese) and now it works fine.
iOS: event1, event2

I don't know the reason, but it seems to be my environmental problem.
I’m sorry for causing you trouble.

**Comment by trap0f** [comment] 2019-08-06 14:17
It's a guess.
EventKit may not have updated the synchronization.
Is there the following processing?

refreshSourcesIfNecessary ()
https://developer.apple.com/documentation/eventkit/ekeventstore/1507421-refreshsourcesifnecessary

**Comment by MaikuB** [comment] 2019-08-13 05:51
may well be, since you seem to have more luck with reproducing the issue, would you be able to debug and see if that solves it and submit a PR?

**Comment by trap0f** [comment] 2019-08-16 03:12
I would like to do so if I could reproduce the event.
But I don't know when I can reproduce it.
At the same time, would you consider adopting 'refreshSourcesIfNecessary()'?

**Comment by MaikuB** [comment] 2019-08-20 02:51
Yes but would need to be able validate it works by reproducing the appropriates scenarios. As you say, right now it's only a guess and there could be other factors at play

**Comment by MaikuB** [comment] 2019-08-20 03:33
Just a note here that I've tried adding an event through an outlook.com account, called `retrieveEvents` and the new event was part of the result even without adding `refreshSourcesIfNecessary` in the iOS code. Wonder if perhaps you're calling `retrieveEvents` as part of `initState` method of the stateful widget that represents a page in your application. If that's the case, note that `initState` isn't invoked when going to back to that page.

**Comment by Brett09** [comment] 2020-01-22 00:20
With the latest release (v3.0.0), haven't noticed such issue. As this ticket is outdated, I'm going to close this. Feel free to open a new ticket if you still experience the issue with the latest release.

Please note that there are few breaking changes in newer versions so make sure to follow the changelogs and examples at pub.dev (https://pub.dev/packages/device_calendar) when you're upgrading the plugin.

**Closed by Brett09** 2020-01-22 00:20 UTC
