### ISSUE TITLE
Calendar ID is not a number for DeleteEvent

### ISSUE THREAD

**Issue by elyctom** [builttoroam/flutter_plugins#123] opened 2019-10-17 06:34 UTC
Whenever I execute **deviceCalendarPlugin.deleteEvent**, I get the following error 

> [599] Device calendar plugin ran into an issue. Platform specific exception [400], with message :"Calendar ID is not a number", has been thrown.

The code I execute is below.

```
var permissionsGranted = await _requestCalendarPermissions();

if (!permissionsGranted) {
   return null;
}

//Attempt to delete the event
var result = await _deviceCalendarPlugin.deleteEvent('4', 'eventId');
```

**Comment by nickrandolph** [comment] 2019-10-17 12:04
Can you try following the example where it retrieves the calendar and uses the id of the calendar in the deleteEvent method?

**Comment by elyctom** [comment] 2019-10-17 12:28
@nickrandolph that's exactly what I did. The '4' as the calendar ID in my example was just for brevity. 

Actually, when I execute the code to retrieve the calendar ID, that's the ID I get. The ID works to create the event just fine, but fails to delete it with that error.

**Comment by nickrandolph** [comment] 2019-10-17 12:46
@elyctom which platform is this on? can you try the other platform (eg if you've been working on iOS can you check to see if the issue is there on Android, and vice versa)

**Comment by elyctom** [comment] 2019-10-17 15:51
@nickrandolph, this is happening on Android. I'm having some pod install issues on iOS now, so as soon as I get that build working I'll confirm the iOS behavior.

**Comment by parth22** [comment] 2019-10-24 09:54
i got this error
```
PlatformException(404, The calendar with the ID 1110 could not be found, null)
```
any idea how to solve this?

**Comment by elyctom** [comment] 2019-11-14 04:03
@nickrandolph it turns out the fault was all my own. Here's what really happened.

- When creating the event, I actually specified an event ID (not knowing that the platform/plugin was going to generate it's own ID for the event and return that ID as a part of the event creation result;
- When I was performing the subsequent deletion, I then used the event ID I had specified, instead of the one returned from the creation result

When I used the event ID from the creation result, it worked just fine. The error provided in the PlatformException is however misleading, since the problem wasn't with the calendar ID, but with the event ID.

**Comment by Brett09** [comment] 2020-01-20 22:27
@elyctom thanks for the update I'll close this issue for now. If you experience the issue again please open a new issue ticket.

**Closed by Brett09** 2020-01-20 22:27 UTC

**Comment by rishita-joshi** [comment] 2023-03-19 09:06
var currentLocation =
        getLocation(await FlutterNativeTimezone.getLocalTimezone());
    setLocalLocation(currentLocation);
    print(currentLocation);

    await Future.delayed(const Duration(seconds: 2));
    var eventToCreate = Event(
      "1",
      //  eventId: "50",
      title: "calendarEventModel 12345",
      description: "eventDescription",
      start: TZDateTime.now(currentLocation),
      end: TZDateTime.now(currentLocation).add(Duration(hours: 10)),
    );

    final createEventResult =
        await deviceCalendarPlugin.createOrUpdateEvent(eventToCreate);
    if (createEventResult!.isSuccess) {
      Utils.showTopMessage("Event added to Calendar", Colors.green);
      Get.back();
    }
  }
  
  
   i used  following packages 
  **device_calendar: ^4.3.0
  flutter_native_timezone:** 
  this is working perfectly in my app. 
  events are created sucessfully and display into my device calendar.

**Comment by IVLIVS-III** [comment] 2023-09-25 20:16
@Inihood1 please file a new issue with more details.

**Comment by rishita-joshi** [comment] 2023-09-26 16:47
> > var currentLocation = getLocation(await FlutterNativeTimezone.getLocalTimezone()); setLocalLocation(currentLocation); print(currentLocation);
> > ```
> > await Future.delayed(const Duration(seconds: 2));
> > var eventToCreate = Event(
> >   "1",
> >   //  eventId: "50",
> >   title: "calendarEventModel 12345",
> >   description: "eventDescription",
> >   start: TZDateTime.now(currentLocation),
> >   end: TZDateTime.now(currentLocation).add(Duration(hours: 10)),
> > );
> > 
> > final createEventResult =
> >     await deviceCalendarPlugin.createOrUpdateEvent(eventToCreate);
> > if (createEventResult!.isSuccess) {
> >   Utils.showTopMessage("Event added to Calendar", Colors.green);
> >   Get.back();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > i used following packages **device_calendar: ^4.3.0 flutter_native_timezone:** this is working perfectly in my app. events are created sucessfully and display into my device calendar.
> 
> Mine is not working. even the imports

please add following depandancy in your project
  device_calendar: ^4.3.0
  flutter_native_timezone:

**Comment by Inihood1** [comment] 2023-09-26 17:43
> > > var currentLocation = getLocation(await FlutterNativeTimezone.getLocalTimezone()); setLocalLocation(currentLocation); print(currentLocation);
> > > ```
> > > await Future.delayed(const Duration(seconds: 2));
> > > var eventToCreate = Event(
> > >   "1",
> > >   //  eventId: "50",
> > >   title: "calendarEventModel 12345",
> > >   description: "eventDescription",
> > >   start: TZDateTime.now(currentLocation),
> > >   end: TZDateTime.now(currentLocation).add(Duration(hours: 10)),
> > > );
> > > 
> > > final createEventResult =
> > >     await deviceCalendarPlugin.createOrUpdateEvent(eventToCreate);
> > > if (createEventResult!.isSuccess) {
> > >   Utils.showTopMessage("Event added to Calendar", Colors.green);
> > >   Get.back();
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > > i used following packages **device_calendar: ^4.3.0 flutter_native_timezone:** this is working perfectly in my app. events are created sucessfully and display into my device calendar.
> > 
> > 
> > Mine is not working. even the imports
> 
> please add following depandancy in your project device_calendar: ^4.3.0 flutter_native_timezone:

Okay,  I'll try it. Thanks

**Comment by Inihood1** [comment] 2023-09-27 07:42
Where is device deviceCalendarPlugin from? I cant see to find it

**Comment by Inihood1** [comment] 2023-09-27 07:46
Also, I need the start and end date to be of a DateTime type. How can I achieve that?

**Comment by Inihood1** [comment] 2023-09-27 15:04
I managed to get it working but after event has been created successfully, I don't see it in my calendar

**Comment by ni3vspace** [comment] 2024-03-04 18:31
> I managed to get it working but after event has been created successfully, I don't see it in my calendar

same issue here on latest version

**Comment by ni3vspace** [comment] 2024-03-05 06:06
I too to get it working but after event has been created successfully, I don't see it in my calendar,
but if eventID remove then it will show, but we want to delete a event then how will delete without id?

**Comment by Ayan4044** [comment] 2025-06-12 11:24
same here doesn't work despite getting success response in calendar it no event is added

**Comment by Ayan4044** [comment] 2025-06-12 11:36
Future<void> _createEvent() async {
  final calendarsResult = await _deviceCalendarPlugin.retrieveCalendars();
  if (calendarsResult.isSuccess) {
    final calendars = calendarsResult.data!;
    final calendar = calendars.first; // Use first available calendar
    
    final event = Event(calendar.id);
    event.title = 'My Event';
    event.description = 'Event description';
    event.start = TZDateTime.now(local).add(Duration(hours: 1));
    event.end = TZDateTime.now(local).add(Duration(hours: 2));
    
    final createEventResult = await _deviceCalendarPlugin.createOrUpdateEvent(event);
    if (createEventResult!.isSuccess) {
      print('Event created successfully');
    }
  }
}

**Comment by erperejildo** [comment] 2026-02-14 11:28
same issue. Any update?
